#!/bin/bash

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then

	bspc monitor eDP1 -d 1 3 5 7 9  
	bspc monitor HDMI1 -d 2 4 6 8 10

else
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

fehbg 
$HOME/.config/polybar/bspwm_launch.sh 
