#! /bin/sh

###---Autostart---###
nm-applet &
xrdb ~/.Xresources &
picom -b --experimental-backends &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	12
bspc config top_padding 		30
bspc config bottom_padding 		30

bspc config split_ratio          	0.52

bspc config focus_follows_pointer	true
bspc config automatic_scheme		alternate
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color 	"#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color 	"#dd2727"
