#! /bin/bash

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

###---Autostart---###
xrdb ~/.Xresources &
xset r rate 300 50 &
numlockx &
#xsetroot -cursor_name left_ptr &
nm-applet &
#bluez &
picom -b &
setxkbmap -option caps:escape &
unclutter &
dunst &
#dropbox &
udiskie -nTa &
mpd &
mpc mount syno nfs://192.168.10.151/volume1/share/Music &
mpc update &
mount Synology &
yams &
emacs --daemon &
blueman-applet &
#autorandr -c &
#onedrive --monitor --sync-shared-folders &
.config/autorandr/postswitch &
#feh --no-fehbg --bg-fill "$HOME/.local/share/bg" &
#$HOME/.config/polybar/bspwm_launch.sh &
export PATH="$PATH:$HOME/scripts" &
$HOME/scripts/fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &

###---MONITORS---###
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

if [[ $(xrandr -q | grep 'HDMI-.* connected') ]]; then
	autorandr -c
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 9 10 
	bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
fi

###---Gaps and borders---###
bspc config border_width         	3
bspc config window_gap          	12
#bspc config top_padding 		30
#bspc config bottom_padding 		40

bspc config split_ratio          	0.52

bspc config focus_follows_pointer	true
bspc config automatic_scheme		alternate
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true

bspc config normal_border_color		"#1d2021"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color 	"#d5c4a1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color 	"#dd2727"

###---Rules---###
#bspc rule -a Kitty:float state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Pavucontrol state=floating

