#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

###---Autostart---###
nm-applet &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
picom -b --experimental-backends &
xset r rate 300 50 &
setxkbmap -option caps:escape &
unclutter &
dunst &
dropbox &
udiskie -nTa &
yams &
emacs --daemon &
blueman-applet &
fehbg &
$HOME/.config/polybar/bspwm_launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

###---MONITORS---###
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
	autorandr -c
fi

###---Gaps and borders---###
bspc config border_width         	2
bspc config window_gap          	12
bspc config top_padding 		30
bspc config bottom_padding 		30

bspc config split_ratio          	0.52

bspc config focus_follows_pointer	true
bspc config automatic_scheme		alternate
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color 	"#EDB83F"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color 	"#dd2727"
